### ISSUE TITLE
Technical report

### ISSUE THREAD

**Issue by Eldo-rado** [fuying-wang/DCXFM#1]
Hi! @fuying-wang  
Do you have any plans to release a technical report related to this repository soon? I noticed that it is about Chest X-ray Foundation Models, and I’ve been reading related papers recently. I hope to learn more about it.

Thank you in advance!

**Comment by fuying-wang** [comment]
Hi,

Thanks for your interest in our work!

Actually, our manuscript is still under review. We will release the manuscript upon it has been accepted. Before that, we will consider releasing a arxiv preprint in the next few days. 

Best regards,
Fuying

**Comment by Eldo-rado** [comment]
Thank you for letting me know. If you release an arXiv preprint, please @ me!
